### ISSUE TITLE
不如ALG

### ISSUE THREAD

**Issue by Molyuu** [world-nb-organization/GaoJiaQi-Archiso#2]
**你们这是什么垃圾东西啊？我看着远不如Arch Linux GUI呢，一群高嘉麒！**

**Comment by Milo2008** [comment]
去去去

**Comment by Milo2008** [comment]
来来来，让我康康你的live CD

**Comment by Molyuu** [comment]
> 来来来，让我康康你的live CD

你是不是高嘉麒啊，够傻逼。你的jsjaro呢

**Comment by aac6fef** [comment]
如果是要做图形化安装，我认为这个项目确实不如ALG，但是，Readme也说了，这是一个我个人自用的iso，我只是想要方便的随时构建，随时使用我最熟悉，最舒服的环境。
